# 탈출에 필요한 플레이어 수
EscapePlayerMaxCount: 3

# 미션 탈출 가능 인원수
MissionEscapeMaxCount: 6

# 헬기 도착지점 반경30칸 랜덤위치 결정 시도 횟수
# 월드보더 안이고 동굴공기가 있어야 성공함. 100번 ,1000번 으로 했을때 실패확률이 높은것같음.
helicopterfindattempt: 100

# 팀에 최대 들어갈수있는 인원수 제한
teamsMaxPlayers : 3

# 팀전에서 미션성공시 공격력 증가하는 량
damagebuff : 3.0