name: EscapeShow
version: 1.5.6
author: rion
main: kr.rion.plugin.Loader
api-version: 1.20
depend: [ Multiverse-Core,NBTAPI,Chunky,voicechat ]

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.25
  - org.jetbrains.kotlin:kotlin-reflect:1.9.25

commands:
  인원설정:
    description: 게임의 탈출인원수랑 미션탈출인원수를 설정합니다.
    usage: /<command> <미션/탈출/팀> <숫자>
    permission: default.op
    permission-message: 이 명령어를 사용할 권한이 없습니다.
  이벤트:
    description: 이벤트를 발생시킵니다.
    usage: /<command> <이벤트이름>
    aliases: [event]
    permission: default.op
    permission-message: 이 명령어를 사용할 권한이 없습니다.
  게임:
    description: 게임GUI를 여는 아이템을 받습니다.
    usage: /<command>
    aliases: [game]
    permission: EscapeShow.Game.GUI
    permission-message: 이 명령어를 사용할 권한이 없습니다.
  미션:
    description: 테스트를 위한 미션수동 명령어입니다.
    usage: /<command> <부여/제거> [player] [missionid]
    aliases: [mission]
    permission: default.op
    permission-message: 이 명령어를 사용할 권한이 없습니다.
  방송:
    description: 거리기반인 음성채팅에서 모든 플레이어에게 들리도록 합니다.
    usage: /<command> [player] [true/false]
    aliases: [bc,broadcast]
    permission: default.op
    permission-message: 이 명령어를 사용할 권한이 없습니다.
  데미지:
    description: 모든플레이어에게 데미지를줍니다
    usage: /<command> <damage>
    aliases: [dmg,damage]
    permission: default.op
    permission-message: 이 명령어를 사용할 권한이 없습니다.
  부활불가:
    description: 모든 플레이어의 부활을 금지시킵니다.(현재 게임에서만 적용)
    usage: /<command>
    aliases: [revivepass,rp]
    permission: default.op
    permission-message: 이 명령어를 사용할 권한이 없습니다.
  게임안내:
    description: 사용자에게 게임에대한 안내를 출력합니다.
    usage: /<command>
    permission: default.true
  아이템:
    description: 사용자에게 아이템에대한 설명을 출력합니다.
    usage: /<command>
    permission: default.true
  조합법:
    description: 사용자에게 조합법을 출력합니다.
    usage: /<command>
    permission: default.true

permissions:
  EscapeShow.Game.GUI:
    description: 게임 관리 GUI를 여는 권한입니다.
    default: op