name: EscapeShow
version: 1.2.0
author: rion
main: kr.rion.plugin.Loader
api-version: 1.20
depend: [Multiverse-Core,NBTAPI,Chunky,voicechat]

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.25
  - org.jetbrains.kotlin:kotlin-reflect:1.9.25

commands:
  탈출인원:
    description: 자동게임종료가 몇명이되어야 탈출하는지 설정하거나 확인합니다.
    usage: /<command> <확인/설정>
    permission: default.op
    permission-message: 이 명령어를 사용할 권한이 없습니다.
  이벤트:
    description: 이벤트를 발생시킵니다.
    usage: /<command> <이벤트이름>
    permission: default.op
    permission-message: 이 명령어를 사용할 권한이 없습니다.
  게임:
    description: 게임GUI를 여는 아이템을 받습니다.
    usage: /<command>
    permission: EscapeShow.Game.GUI
    permission-message: 이 명령어를 사용할 권한이 없습니다.

permissions:
  EscapeShow.Game.GUI:
    description: 게임 관리 GUI를 여는 권한입니다.
    default: op